### ISSUE TITLE
[ci][github][action][workflow] github action intro

### ISSUE THREAD

**Issue by konosubakonoakua** [konosubakonoakua/blog#55]
## how to add manual trigger
need `workflow_dispatch`.
```yaml
name: update lockfile
on:
  # Scheduled update (each day)
  schedule: [{ cron: "30 01 * * *" }]
  workflow_dispatch:
```
